[2023-03-03T16:51:52.154+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: python_operator.hello_with_python manual__2023-03-03T16:51:51.691584+00:00 [queued]>
[2023-03-03T16:51:52.165+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: python_operator.hello_with_python manual__2023-03-03T16:51:51.691584+00:00 [queued]>
[2023-03-03T16:51:52.165+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T16:51:52.165+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2023-03-03T16:51:52.165+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-03T16:51:52.179+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): hello_with_python> on 2023-03-03 16:51:51.691584+00:00
[2023-03-03T16:51:52.184+0000] {standard_task_runner.py:55} INFO - Started process 10258 to run task
[2023-03-03T16:51:52.188+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'python_operator', 'hello_with_python', 'manual__2023-03-03T16:51:51.691584+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/watch_tfp_services.py', '--cfg-path', '/tmp/tmpysurpx_8']
[2023-03-03T16:51:52.188+0000] {standard_task_runner.py:83} INFO - Job 45: Subtask hello_with_python
[2023-03-03T16:51:52.257+0000] {task_command.py:388} INFO - Running <TaskInstance: python_operator.hello_with_python manual__2023-03-03T16:51:51.691584+00:00 [running]> on host b5a34fc27f57
[2023-03-03T16:51:52.336+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=python_operator
AIRFLOW_CTX_TASK_ID=hello_with_python
AIRFLOW_CTX_EXECUTION_DATE=2023-03-03T16:51:51.691584+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-03T16:51:51.691584+00:00
[2023-03-03T16:51:52.337+0000] {logging_mixin.py:137} INFO - Hello people from python funtion
[2023-03-03T16:51:52.337+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/watch_tfp_services.py", line 19, in print_hello
    req = requests.request(method, url, headers=headers, auth=None)
NameError: name 'method' is not defined
[2023-03-03T16:51:52.345+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=python_operator, task_id=hello_with_python, execution_date=20230303T165151, start_date=20230303T165152, end_date=20230303T165152
[2023-03-03T16:51:52.356+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 45 for task hello_with_python (name 'method' is not defined; 10258)
[2023-03-03T16:51:52.399+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-03T16:51:52.419+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
